GFM-200: Выделять стрелочки разметки, которые отвечают за кадрирование
bitia-ru/gekkon-m-frontend pull request #201
Opened 2021-02-22 17:58 UTC by SvetlanaBatova

2021-02-25 13:31 UTC, levenkov requested changes

2021-02-25 13:31 UTC, levenkov commented on src/v2/components/RouteEditor/RouteEditor.js
> +                                isStart={[0,1].includes(index)}
Я предлагаю выделить логику проверки, является ли маркер стартовым, в отдельную функцию, в которую передавать не только индекс, но и сам маркер. Пока будет использоваться только индекс, но в дальнейшем мы скорее всего сделаем, чтобы можно было принудительно задавать тип маркера.

И даже скорее сделать не isStart, pointerType, который будет возвращать `regular` для обычных маркеров и `start` для стартовых.

Впоследствии будет ещё как минимум `top` и `bonus`.

И внутри `<Marker>` сделать добавление типа маркера как можно более простым. Чтобы тип являлся частью имени файла иконки маркера и т.п.

2021-02-25 20:06 UTC, SvetlanaBatova commented on src/v2/components/RouteEditor/RouteEditor.js
> +                                isStart={[0,1].includes(index)}
Переделала на такой вариант, только кажется логичным в функцию, которая определяет тип маркера передавать не только индекс и маркер, но и параметр editable, т.е. является ли это маркер маркером редактируемой трассы или трассы в режиме просмотра. Сейчас, если я правильно понимаю, стартовые маркеры должны выделяться только в режиме редактирования, поэтому сделала так, что тип маркера полностью определяется функцией, в которую передаются editable, index, pointer. В самом компоненте маркера просто отображается тот тип маркера, который передан через пропсы (по нему определяется имя файла со стрелочкой)

2021-03-02 22:18 UTC, levenkov approved these changes

2021-03-02 22:18 UTC, merged